// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TutorWindow
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTutorWindowPackageString = "9f974634-d607-4bd8-9e7a-3256636d2a36";
        public static Guid guidTutorWindowPackage = new Guid(guidTutorWindowPackageString);

        public const string guidTutorWindowPackageCmdSetString = "22a80735-714e-4db4-9b83-c5d0dc1652d6";
        public static Guid guidTutorWindowPackageCmdSet = new Guid(guidTutorWindowPackageCmdSetString);

        public const string guidImagesString = "fe89046a-a4e7-42ce-a2ea-cc1a4a987969";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TutorToolWindowCommandId = 0x0100;
        public const int logo = 0x0001;
    }
}