//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pendant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PendantResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PendantResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pendant.PendantResources", typeof(PendantResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommentsAnalyzer Category.
        /// </summary>
        internal static string COM_Category {
            get {
                return ResourceManager.GetString("COM-Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation: {0}.
        /// </summary>
        internal static string COM_MessageFormat {
            get {
                return ResourceManager.GetString("COM-MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Violation.
        /// </summary>
        internal static string COM_Title {
            get {
                return ResourceManager.GetString("COM-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamingConventionAnalyzer Category.
        /// </summary>
        internal static string NAM_Category {
            get {
                return ResourceManager.GetString("NAM-Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation: {0}.
        /// </summary>
        internal static string NAM_MessageFormat {
            get {
                return ResourceManager.GetString("NAM-MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming Convention Violation.
        /// </summary>
        internal static string NAM_Title {
            get {
                return ResourceManager.GetString("NAM-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertySelfReferenceAnalyzer Category.
        /// </summary>
        internal static string PSR_Category {
            get {
                return ResourceManager.GetString("PSR-Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation: {0}.
        /// </summary>
        internal static string PSR_MessageFormat {
            get {
                return ResourceManager.GetString("PSR-MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Self Reference Violation.
        /// </summary>
        internal static string PSR_Title {
            get {
                return ResourceManager.GetString("PSR-Title", resourceCulture);
            }
        }
    }
}
